apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: baemin
  labels:
    app: notification-service
    {{- include "baemin.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path:   "/actuator/prometheus"
        prometheus.io/port:   "8084"
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.images.registry }}/notification-service:{{ .Values.images.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: NOTIF_DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET
            - name: BFF_HMAC_NOTIF_SECRET
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: BFF_HMAC_NOTIF_SECRET
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
            - name: JAVA_OPTS
              value: "-Xms32m -Xmx200m"
