apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: notification-service
  namespace: baemin
  labels:
    app: notification-service
    {{- include "baemin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: notification-service
  strategy:
    blueGreen:
      activeService: notification-service-active
      previewService: notification-service-preview
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path:   "/actuator/prometheus"
        prometheus.io/port:   "8084"
    spec:
      containers:
        - name: notification-service
          image: "{{ .Values.images.registry }}/notification-service:{{ .Values.images.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: NOTIF_DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET
            - name: BFF_HMAC_NOTIF_SECRET
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: BFF_HMAC_NOTIF_SECRET
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 60
            failureThreshold: 60
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
