apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user-service
  namespace: baemin
  labels:
    app: user-service
    {{- include "baemin.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: {{ .Values.userReplicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: user-service
  strategy:
    canary:
      stableService: user-service-active
      canaryService: user-service-canary
      analysis:
        templates:
          - templateName: user-service-error-rate
        startingStep: 1
        args:
          - name: canary-hash
            valueFrom:
              podTemplateHashValue: Latest
      steps:
        - setWeight: 50
        - pause:
            duration: 6m
        - setWeight: 100
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path:   "/actuator/prometheus"
        prometheus.io/port:   "8081"
    spec:
      containers:
        - name: user-service
          image: "{{ .Values.images.registry }}/user-service:{{ .Values.images.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: USER_DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: common-secret
                  key: JWT_SECRET
            - name: BFF_HMAC_USER_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-secret
                  key: BFF_HMAC_USER_SECRET
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            failureThreshold: 60
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
