server:
  port: 8084

spring:
  application:
    name: notification-service
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "common.event"
        spring.json.value.default.type: "common.event.OrderEvent"
  profiles:
    default: dev
    group:
      dev:  [pgsql-dev,  jwt-dev,  hmac-dev,  redis-dev]
      test: [pgsql-test, jwt-test, hmac-test, redis-test]
      prod: [pgsql-prod, jwt-prod, hmac-prod, redis-prod]
  config:
    import:
      - "pgsql.yaml"
      - "jwt.yaml"
      - "hmac.yaml"
      - "redis.yaml"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
