server:
  port: 8084

spring:
  application:
    name: notification-service
  mvc:
    problemdetails:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    default: dev
    group:
      dev:  [pgsql-dev,  jwt-dev]
      test: [pgsql-test, jwt-test]
      prod: [pgsql-prod, jwt-prod]
  config:
    import:
      - "pgsql.yaml"
      - "jwt.yaml"
