---
spring:
  config:
    activate:
      on-profile: "redis-dev"
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: "redis-test"
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
---
spring:
  config:
    activate:
      on-profile: "redis-prod"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
