services:
  user-db:
    image: postgres:16
    container_name: baemin_user_db
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user_svc
      POSTGRES_PASSWORD: userpass
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  store-db:
    image: postgres:16
    container_name: baemin_store_db
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: store_svc
      POSTGRES_PASSWORD: storepass
    ports:
      - "5434:5432"
    volumes:
      - store_db_data:/var/lib/postgresql/data

  order-db:
    image: postgres:16
    container_name: baemin_order_db
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: order_svc
      POSTGRES_PASSWORD: orderpass
    ports:
      - "5435:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

volumes:
  user_db_data:
  store_db_data:
  order_db_data:
