apiVersion: v1
kind: Secret
metadata:
  name: bff-secret
  namespace: baemin
type: Opaque
stringData:
  BFF_HMAC_USER_SECRET: "changeme"
  BFF_HMAC_STORE_SECRET: "changeme"
  BFF_HMAC_ORDER_SECRET: "changeme"
  BFF_HMAC_NOTIF_SECRET: "changeme"
