server:
  port: 8080

spring:
  application:
    name: Baemin
  datasource:
    url: jdbc:postgresql://localhost:5433/food
    username: food
    password: foodpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug