server:
  port: 8080

spring:
  application:
    name: Baemin
  datasource:
    url: jdbc:postgresql://localhost:5433/food
    username: food
    password: foodpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "baemin-jwt-secret-key-must-be-at-least-32-characters-long"
  expiration-ms: 86400000  # 24 hours

logging:
  level:
    org.hibernate.SQL: debug