images:
  registry: prolmpa
  tag: "1f03e18cfb2b"

replicas: 1
javaOpts: "-Xms128m -Xmx512m"

secrets:
  hmacUser:  "changeme"
  hmacStore: "changeme"
  hmacOrder: "changeme"
  hmacNotif: "changeme"
  hmacAi:    "changeme"
