image:
  repository: apache/kafka
  tag: "3.7.1"

service:
  port: 9092

kafka:
  nodeId: 1
  offsetsTopicReplicationFactor: 1
  transactionStateLogReplicationFactor: 1
  transactionStateLogMinIsr: 1
  autoCreateTopicsEnable: true
