global:
  imageRegistry: oci.bitnami.com

kafka:
  replicaCount: 1
  kraft:
    enabled: true
  listeners:
    client:
      protocol: PLAINTEXT
  persistence:
    size: 5Gi
  provisioning:
    enabled: true
    topics:
      - name: baemin.order.events
        partitions: 3
        replicationFactor: 1
        config:
          retention.ms: "604800000"
          cleanup.policy: delete