apiVersion: v1
kind: Secret
metadata:
  name: bff-secret
  namespace: baemin
  labels:
    {{- include "baemin.labels" . | nindent 4 }}
type: Opaque
stringData:
  BFF_HMAC_USER_SECRET:  {{ .Values.secrets.bff.hmacUser  | quote }}
  BFF_HMAC_STORE_SECRET: {{ .Values.secrets.bff.hmacStore | quote }}
  BFF_HMAC_ORDER_SECRET: {{ .Values.secrets.bff.hmacOrder | quote }}
  BFF_HMAC_NOTIF_SECRET: {{ .Values.secrets.bff.hmacNotif | quote }}
  BFF_HMAC_AI_SECRET:    {{ .Values.secrets.bff.hmacAi    | quote }}
