apiVersion: v1
kind: Secret
metadata:
  name: common-secret
  namespace: baemin
  labels:
    {{- include "baemin.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwt | quote }}
