apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: baemin
  labels:
    {{- include "baemin.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME:           {{ .Values.secrets.notification.dbUser    | quote }}
  DB_PASSWORD:           {{ .Values.secrets.notification.dbPass    | quote }}
  BFF_HMAC_NOTIF_SECRET: {{ .Values.secrets.notification.hmacNotif | quote }}
