{{- include "baemin.secretMeta" (dict "name" "notification-secret" "root" .) }}
  DB_USERNAME:           {{ .Values.secrets.notification.dbUser    | quote }}
  DB_PASSWORD:           {{ .Values.secrets.notification.dbPass    | quote }}
  BFF_HMAC_NOTIF_SECRET: {{ .Values.secrets.notification.hmacNotif | quote }}
