apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: baemin
  labels:
    {{- include "baemin.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME:           {{ .Values.secrets.order.dbUser    | quote }}
  DB_PASSWORD:           {{ .Values.secrets.order.dbPass    | quote }}
  BFF_HMAC_ORDER_SECRET: {{ .Values.secrets.order.hmacOrder | quote }}
