{{- include "baemin.secretMeta" (dict "name" "store-secret" "root" .) }}
  DB_USERNAME:           {{ .Values.secrets.store.dbUser    | quote }}
  DB_PASSWORD:           {{ .Values.secrets.store.dbPass    | quote }}
  BFF_HMAC_STORE_SECRET: {{ .Values.secrets.store.hmacStore | quote }}
