apiVersion: v1
kind: Secret
metadata:
  name: store-secret
  namespace: baemin
  labels:
    {{- include "baemin.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME:           {{ .Values.secrets.store.dbUser    | quote }}
  DB_PASSWORD:           {{ .Values.secrets.store.dbPass    | quote }}
  BFF_HMAC_STORE_SECRET: {{ .Values.secrets.store.hmacStore | quote }}
