{{- include "baemin.secretMeta" (dict "name" "user-secret" "root" .) }}
  DB_USERNAME:          {{ .Values.secrets.user.dbUser   | quote }}
  DB_PASSWORD:          {{ .Values.secrets.user.dbPass   | quote }}
  BFF_HMAC_USER_SECRET: {{ .Values.secrets.user.hmacUser | quote }}