server:
  port: 8080

spring:
  application:
    name: bff-service
  mvc:
    problemdetails:
      enabled: true
  profiles:
    default: dev
    group:
      dev:  [backend-dev,  hmac-dev]
      test: [backend-test, hmac-test]
      prod: [backend-prod, hmac-prod]
  config:
    import:
      - "backend.yaml"
      - "hmac.yaml"
