server:
  port: 8080

spring:
  application:
    name: bff-service
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceInitializationAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration
  mvc:
    problemdetails:
      enabled: true
  profiles:
    default: dev
    group:
      dev:  [backend-dev,  hmac-dev]
      test: [backend-test, hmac-test]
      prod: [backend-prod, hmac-prod]
  config:
    import:
      - "backend.yaml"
      - "hmac.yaml"

resilience4j:
  circuitbreaker:
    instances:
      notification:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 3s
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
