server:
  port: 8080

spring:
  application:
    name: bff-service
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceInitializationAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.data.jpa.autoconfigure.DataJpaRepositoriesAutoConfiguration
  mvc:
    problemdetails:
      enabled: true
  profiles:
    default: dev
    group:
      dev:  [backend-dev,  hmac-dev]
      test: [backend-test, hmac-test]
      prod: [backend-prod, hmac-prod]
  config:
    import:
      - "backend.yaml"
      - "hmac.yaml"
