---
spring:
  config:
    activate:
      on-profile: "backend-dev"
backend:
  user-service:
    url: http://localhost:8081
  store-service:
    url: http://localhost:8082
  order-service:
    url: http://localhost:8083
  notification-service:
    url: http://localhost:8084
---
spring:
  config:
    activate:
      on-profile: "backend-test"
backend:
  user-service:
    url: http://localhost:8081
  store-service:
    url: http://localhost:8082
  order-service:
    url: http://localhost:8083
  notification-service:
    url: http://localhost:8084
---
spring:
  config:
    activate:
      on-profile: "backend-prod"
backend:
  user-service:
    url: http://192.168.160.101:8081
  store-service:
    url: http://192.168.160.102:8082
  order-service:
    url: http://192.168.160.103:8083
  notification-service:
    url: http://192.168.160.104:8084
