---
spring:
  config:
    activate:
      on-profile: "hmac-dev"
bff.hmac:
  user-secret:         "baemin-bff-user-hmac-secret-key-32chars+"
  store-secret:        "baemin-bff-store-hmac-secret-key-32chars+"
  order-secret:        "baemin-bff-order-hmac-secret-key-32chars+"
  notification-secret: "baemin-bff-notif-hmac-secret-key-32chars+"
---
spring:
  config:
    activate:
      on-profile: "hmac-test"
bff.hmac:
  user-secret:         ${BFF_HMAC_USER_SECRET}
  store-secret:        ${BFF_HMAC_STORE_SECRET}
  order-secret:        ${BFF_HMAC_ORDER_SECRET}
  notification-secret: ${BFF_HMAC_NOTIF_SECRET}
---
spring:
  config:
    activate:
      on-profile: "hmac-prod"
bff.hmac:
  user-secret:         ${BFF_HMAC_USER_SECRET}
  store-secret:        ${BFF_HMAC_STORE_SECRET}
  order-secret:        ${BFF_HMAC_ORDER_SECRET}
  notification-secret: ${BFF_HMAC_NOTIF_SECRET}
