global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]

rule_files:
  - alerting-rules.yml

scrape_configs:
  - job_name: bff-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${BFF_IP}:8080"]

  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${USER_IP}:8081"]

  - job_name: store-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${STORE_IP}:8082"]

  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${ORDER_IP}:8083"]

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["${NOTIFICATION_IP}:8084"]
