---
spring:
  config:
    activate:
      on-profile: "hmac-dev"
bff.hmac:
  ai-secret:    "baemin-bff-ai-hmac-secret-key-32chars++"
  store-secret: "baemin-bff-store-hmac-secret-key-32chars+"
  order-secret: "baemin-bff-order-hmac-secret-key-32chars+"
---
spring:
  config:
    activate:
      on-profile: "hmac-prod"
bff.hmac:
  ai-secret:    ${BFF_HMAC_AI_SECRET}
  store-secret: ${HMAC_STORE_SECRET}
  order-secret: ${HMAC_ORDER_SECRET}
