apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-urls
  namespace: baemin
data:
  USER_SERVICE_URL: "http://user-service:8081"
  STORE_SERVICE_URL: "http://store-service:8082"
  ORDER_SERVICE_URL: "http://order-service:8083"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8084"
