apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: baemin
data:
  USER_DB_URL: "jdbc:postgresql://192.168.160.101:5432/userdb"
  STORE_DB_URL: "jdbc:postgresql://192.168.160.102:5432/storedb"
  ORDER_DB_URL: "jdbc:postgresql://192.168.160.103:5432/orderdb"
  NOTIF_DB_URL: "jdbc:postgresql://192.168.160.104:5432/notificationdb"
