images:
  registry: prolmpa
  tag: "1f03e18cfb2b"

replicas: 1
javaOpts: "-Xms128m -Xmx512m"

config:
  dbUrl: "jdbc:postgresql://192.168.160.103:5432/orderdb"
  kafkaBootstrapServers: "baemin-kafka:9092"

secrets:
  dbUser:    "changeme"
  dbPass:    "changeme"
  hmacOrder: "changeme"
