images:
  registry: prolmpa
  tag: "734eec26f463"

replicas: 1
javaOpts: "-Xms128m -Xmx512m"

config:
  dbUrl: "jdbc:postgresql://192.168.160.103:5432/orderdb"

secrets:
  dbUser:    "changeme"
  dbPass:    "changeme"
  hmacOrder: "changeme"
