CREATE TABLE IF NOT EXISTS stores
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT       NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    address              VARCHAR(255) NOT NULL,
    phone                VARCHAR(20)  NOT NULL,
    content              TEXT         NOT NULL,
    status               VARCHAR(50)  NOT NULL,
    store_picture_url    VARCHAR(500),
    product_created_time BIGINT       NOT NULL,
    opened_time          BIGINT       NOT NULL,
    closed_time          BIGINT       NOT NULL,
    closed_days          VARCHAR(50)  NOT NULL,
    created_at           BIGINT       NOT NULL,
    updated_at           BIGINT       NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_stores_user_id ON stores (user_id);

CREATE TABLE IF NOT EXISTS products
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id            BIGINT       NOT NULL REFERENCES stores (id),
    name                VARCHAR(100) NOT NULL,
    description         TEXT         NOT NULL,
    price               INT          NOT NULL,
    product_picture_url VARCHAR(500),
    popularity          INT          NOT NULL,
    status              BOOLEAN      NOT NULL,
    created_at          BIGINT       NOT NULL,
    updated_at          BIGINT       NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_products_store_id ON products (store_id);
CREATE INDEX IF NOT EXISTS idx_products_popularity ON products (popularity DESC);

CREATE TABLE IF NOT EXISTS reviews
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id   BIGINT NOT NULL REFERENCES stores (id),
    user_id    BIGINT NOT NULL,
    rating     INT    NOT NULL,
    content    TEXT   NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reviews_store_id ON reviews (store_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews (user_id);
