server:
  port: 8081

spring:
  application:
    name: user-service
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: user_svc
    password: userpass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "baemin-jwt-secret-key-must-be-at-least-32-characters-long"
  expiration-ms: 86400000
