---
spring:
  config:
    activate:
      on-profile: "pgsql-dev"
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: user_svc
    password: userpass
---
spring:
  config:
    activate:
      on-profile: "pgsql-test"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: "pgsql-prod"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
