---
spring:
  config:
    activate:
      on-profile: "pgsql-dev"
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: user_svc
    password: userpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: "pgsql-test"
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: user_svc
    password: userpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: "pgsql-prod"
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: user_svc
    password: userpass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
