images:
  registry: prolmpa
  tag: "d8015fc8d86e"

replicas: 1
javaOpts: "-Xms128m -Xmx512m"

config:
  dbUrl: "jdbc:postgresql://192.168.160.101:5432/userdb"

secrets:
  dbUser:   "changeme"
  dbPass:   "changeme"
  hmacUser: "changeme"
