server:
  port: 8083

spring:
  application:
    name: order-service
  mvc:
    problemdetails:
      enabled: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    default: dev
    group:
      dev:  [pgsql-dev,  jwt-dev,  hmac-dev,  cache-dev]
      test: [pgsql-test, jwt-test, hmac-test]
      prod: [pgsql-prod, jwt-prod, hmac-prod, cache-prod]
  config:
    import:
      - "pgsql.yaml"
      - "jwt.yaml"
      - "hmac.yaml"
      - "cache.yml"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      probes:
        enabled: true
