---
spring:
  config:
    activate:
      on-profile: "pgsql-dev"
  datasource:
    url: jdbc:postgresql://localhost:5435/orderdb
    username: order_svc
    password: orderpass
---
spring:
  config:
    activate:
      on-profile: "pgsql-test"
  datasource:
    url: jdbc:postgresql://localhost:5435/orderdb
    username: order_svc
    password: orderpass
---
spring:
  config:
    activate:
      on-profile: "pgsql-prod"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
