CREATE TABLE IF NOT EXISTS carts
(
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT  NOT NULL UNIQUE,
    store_id   BIGINT  NOT NULL,
    is_ordered BOOLEAN NOT NULL,
    created_at BIGINT  NOT NULL,
    updated_at BIGINT  NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_products
(
    id         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id    BIGINT NOT NULL REFERENCES carts (id),
    product_id BIGINT NOT NULL,
    quantity   BIGINT NOT NULL,
    unit_price BIGINT NOT NULL,
    CONSTRAINT uq_cp_cart_product UNIQUE (cart_id, product_id)
);

CREATE TABLE IF NOT EXISTS orders
(
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id     BIGINT      NOT NULL UNIQUE REFERENCES carts (id),
    user_id     BIGINT      NOT NULL,
    store_id    BIGINT      NOT NULL,
    total_price BIGINT      NOT NULL,
    status      VARCHAR(30) NOT NULL,
    created_at  BIGINT      NOT NULL,
    updated_at  BIGINT      NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_orders_store_status ON orders (store_id, status);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);
