apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baemin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/proLmpa/Deliprac.git
    targetRevision: main
    path: helm/baemin
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: baemin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
