apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "{{ .Values.metrics.port }}"
        prometheus.io/path:   "/metrics"
    spec:
      containers:
        - name: kafka-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--kafka.server={{ .Values.kafka.server }}"
          ports:
            - containerPort: {{ .Values.metrics.port }}
              name: metrics
