{{- if .Values.prometheusOperator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-service
  namespace: baemin
  labels:
    app: notification-service
    release: prometheus-agent
    {{- include "baemin.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: notification-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
{{- end }}
