apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: baemin
spec:
  type: NodePort
  selector:
    app: bff-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
