apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: baemin
type: Opaque
stringData:
  DB_URL:                {{ .Values.config.dbUrl | quote }}
  DB_USERNAME:           {{ .Values.secrets.dbUser | quote }}
  DB_PASSWORD:           {{ .Values.secrets.dbPass | quote }}
  BFF_HMAC_ORDER_SECRET: {{ .Values.secrets.hmacOrder | quote }}
