store:
  cache:
    redis-ttl-minutes: 5
    list-ttl-minutes: 2

---
spring:
  config:
    activate:
      on-profile: "cache-dev"
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: "cache-prod"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}