---
spring:
  config:
    activate:
      on-profile: "pgsql-dev"
  datasource:
    url: jdbc:postgresql://localhost:5434/storedb
    username: store_svc
    password: storepass
---
spring:
  config:
    activate:
      on-profile: "pgsql-test"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: "pgsql-prod"
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
