---
spring:
  config:
    activate:
      on-profile: "pgsql-dev"
  datasource:
    url: jdbc:postgresql://localhost:5434/storedb
    username: store_svc
    password: storepass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: "pgsql-test"
  datasource:
    url: jdbc:postgresql://localhost:5434/storedb
    username: store_svc
    password: storepass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: "pgsql-prod"
  datasource:
    url: jdbc:postgresql://localhost:5434/storedb
    username: store_svc
    password: storepass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
