apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: baemin
  labels:
    {{- include "baemin.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | quote }}
